---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/bruno/Documents/ESIEE/Computer Graphics and OpenGL/TP1/app'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003E70, symSize: 0xCC }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003E70, symSize: 0xCC }
...
